/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.sg.secram.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ReadHeaderAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReadHeaderAvro\",\"namespace\":\"com.sg.secram.avro\",\"fields\":[{\"name\":\"Order\",\"type\":\"int\"},{\"name\":\"Ref_len\",\"type\":\"int\"},{\"name\":\"Next_POS\",\"type\":\"long\"},{\"name\":\"Bin_mq_nl\",\"type\":\"int\"},{\"name\":\"Read_Name\",\"type\":\"string\"},{\"name\":\"Flag\",\"type\":\"int\"},{\"name\":\"TLen\",\"type\":\"int\"},{\"name\":\"Tags\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int Order;
  @Deprecated public int Ref_len;
  @Deprecated public long Next_POS;
  @Deprecated public int Bin_mq_nl;
  @Deprecated public java.lang.CharSequence Read_Name;
  @Deprecated public int Flag;
  @Deprecated public int TLen;
  @Deprecated public java.nio.ByteBuffer Tags;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ReadHeaderAvro() {}

  /**
   * All-args constructor.
   */
  public ReadHeaderAvro(java.lang.Integer Order, java.lang.Integer Ref_len, java.lang.Long Next_POS, java.lang.Integer Bin_mq_nl, java.lang.CharSequence Read_Name, java.lang.Integer Flag, java.lang.Integer TLen, java.nio.ByteBuffer Tags) {
    this.Order = Order;
    this.Ref_len = Ref_len;
    this.Next_POS = Next_POS;
    this.Bin_mq_nl = Bin_mq_nl;
    this.Read_Name = Read_Name;
    this.Flag = Flag;
    this.TLen = TLen;
    this.Tags = Tags;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Order;
    case 1: return Ref_len;
    case 2: return Next_POS;
    case 3: return Bin_mq_nl;
    case 4: return Read_Name;
    case 5: return Flag;
    case 6: return TLen;
    case 7: return Tags;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Order = (java.lang.Integer)value$; break;
    case 1: Ref_len = (java.lang.Integer)value$; break;
    case 2: Next_POS = (java.lang.Long)value$; break;
    case 3: Bin_mq_nl = (java.lang.Integer)value$; break;
    case 4: Read_Name = (java.lang.CharSequence)value$; break;
    case 5: Flag = (java.lang.Integer)value$; break;
    case 6: TLen = (java.lang.Integer)value$; break;
    case 7: Tags = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Order' field.
   */
  public java.lang.Integer getOrder() {
    return Order;
  }

  /**
   * Sets the value of the 'Order' field.
   * @param value the value to set.
   */
  public void setOrder(java.lang.Integer value) {
    this.Order = value;
  }

  /**
   * Gets the value of the 'Ref_len' field.
   */
  public java.lang.Integer getRefLen() {
    return Ref_len;
  }

  /**
   * Sets the value of the 'Ref_len' field.
   * @param value the value to set.
   */
  public void setRefLen(java.lang.Integer value) {
    this.Ref_len = value;
  }

  /**
   * Gets the value of the 'Next_POS' field.
   */
  public java.lang.Long getNextPOS() {
    return Next_POS;
  }

  /**
   * Sets the value of the 'Next_POS' field.
   * @param value the value to set.
   */
  public void setNextPOS(java.lang.Long value) {
    this.Next_POS = value;
  }

  /**
   * Gets the value of the 'Bin_mq_nl' field.
   */
  public java.lang.Integer getBinMqNl() {
    return Bin_mq_nl;
  }

  /**
   * Sets the value of the 'Bin_mq_nl' field.
   * @param value the value to set.
   */
  public void setBinMqNl(java.lang.Integer value) {
    this.Bin_mq_nl = value;
  }

  /**
   * Gets the value of the 'Read_Name' field.
   */
  public java.lang.CharSequence getReadName() {
    return Read_Name;
  }

  /**
   * Sets the value of the 'Read_Name' field.
   * @param value the value to set.
   */
  public void setReadName(java.lang.CharSequence value) {
    this.Read_Name = value;
  }

  /**
   * Gets the value of the 'Flag' field.
   */
  public java.lang.Integer getFlag() {
    return Flag;
  }

  /**
   * Sets the value of the 'Flag' field.
   * @param value the value to set.
   */
  public void setFlag(java.lang.Integer value) {
    this.Flag = value;
  }

  /**
   * Gets the value of the 'TLen' field.
   */
  public java.lang.Integer getTLen() {
    return TLen;
  }

  /**
   * Sets the value of the 'TLen' field.
   * @param value the value to set.
   */
  public void setTLen(java.lang.Integer value) {
    this.TLen = value;
  }

  /**
   * Gets the value of the 'Tags' field.
   */
  public java.nio.ByteBuffer getTags() {
    return Tags;
  }

  /**
   * Sets the value of the 'Tags' field.
   * @param value the value to set.
   */
  public void setTags(java.nio.ByteBuffer value) {
    this.Tags = value;
  }

  /** Creates a new ReadHeaderAvro RecordBuilder */
  public static com.sg.secram.avro.ReadHeaderAvro.Builder newBuilder() {
    return new com.sg.secram.avro.ReadHeaderAvro.Builder();
  }
  
  /** Creates a new ReadHeaderAvro RecordBuilder by copying an existing Builder */
  public static com.sg.secram.avro.ReadHeaderAvro.Builder newBuilder(com.sg.secram.avro.ReadHeaderAvro.Builder other) {
    return new com.sg.secram.avro.ReadHeaderAvro.Builder(other);
  }
  
  /** Creates a new ReadHeaderAvro RecordBuilder by copying an existing ReadHeaderAvro instance */
  public static com.sg.secram.avro.ReadHeaderAvro.Builder newBuilder(com.sg.secram.avro.ReadHeaderAvro other) {
    return new com.sg.secram.avro.ReadHeaderAvro.Builder(other);
  }
  
  /**
   * RecordBuilder for ReadHeaderAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReadHeaderAvro>
    implements org.apache.avro.data.RecordBuilder<ReadHeaderAvro> {

    private int Order;
    private int Ref_len;
    private long Next_POS;
    private int Bin_mq_nl;
    private java.lang.CharSequence Read_Name;
    private int Flag;
    private int TLen;
    private java.nio.ByteBuffer Tags;

    /** Creates a new Builder */
    private Builder() {
      super(com.sg.secram.avro.ReadHeaderAvro.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.sg.secram.avro.ReadHeaderAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Order)) {
        this.Order = data().deepCopy(fields()[0].schema(), other.Order);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Ref_len)) {
        this.Ref_len = data().deepCopy(fields()[1].schema(), other.Ref_len);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Next_POS)) {
        this.Next_POS = data().deepCopy(fields()[2].schema(), other.Next_POS);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Bin_mq_nl)) {
        this.Bin_mq_nl = data().deepCopy(fields()[3].schema(), other.Bin_mq_nl);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Read_Name)) {
        this.Read_Name = data().deepCopy(fields()[4].schema(), other.Read_Name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.Flag)) {
        this.Flag = data().deepCopy(fields()[5].schema(), other.Flag);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.TLen)) {
        this.TLen = data().deepCopy(fields()[6].schema(), other.TLen);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.Tags)) {
        this.Tags = data().deepCopy(fields()[7].schema(), other.Tags);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ReadHeaderAvro instance */
    private Builder(com.sg.secram.avro.ReadHeaderAvro other) {
            super(com.sg.secram.avro.ReadHeaderAvro.SCHEMA$);
      if (isValidValue(fields()[0], other.Order)) {
        this.Order = data().deepCopy(fields()[0].schema(), other.Order);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Ref_len)) {
        this.Ref_len = data().deepCopy(fields()[1].schema(), other.Ref_len);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Next_POS)) {
        this.Next_POS = data().deepCopy(fields()[2].schema(), other.Next_POS);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Bin_mq_nl)) {
        this.Bin_mq_nl = data().deepCopy(fields()[3].schema(), other.Bin_mq_nl);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Read_Name)) {
        this.Read_Name = data().deepCopy(fields()[4].schema(), other.Read_Name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.Flag)) {
        this.Flag = data().deepCopy(fields()[5].schema(), other.Flag);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.TLen)) {
        this.TLen = data().deepCopy(fields()[6].schema(), other.TLen);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.Tags)) {
        this.Tags = data().deepCopy(fields()[7].schema(), other.Tags);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'Order' field */
    public java.lang.Integer getOrder() {
      return Order;
    }
    
    /** Sets the value of the 'Order' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder setOrder(int value) {
      validate(fields()[0], value);
      this.Order = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'Order' field has been set */
    public boolean hasOrder() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'Order' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder clearOrder() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'Ref_len' field */
    public java.lang.Integer getRefLen() {
      return Ref_len;
    }
    
    /** Sets the value of the 'Ref_len' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder setRefLen(int value) {
      validate(fields()[1], value);
      this.Ref_len = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'Ref_len' field has been set */
    public boolean hasRefLen() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'Ref_len' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder clearRefLen() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'Next_POS' field */
    public java.lang.Long getNextPOS() {
      return Next_POS;
    }
    
    /** Sets the value of the 'Next_POS' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder setNextPOS(long value) {
      validate(fields()[2], value);
      this.Next_POS = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'Next_POS' field has been set */
    public boolean hasNextPOS() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'Next_POS' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder clearNextPOS() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'Bin_mq_nl' field */
    public java.lang.Integer getBinMqNl() {
      return Bin_mq_nl;
    }
    
    /** Sets the value of the 'Bin_mq_nl' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder setBinMqNl(int value) {
      validate(fields()[3], value);
      this.Bin_mq_nl = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'Bin_mq_nl' field has been set */
    public boolean hasBinMqNl() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'Bin_mq_nl' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder clearBinMqNl() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'Read_Name' field */
    public java.lang.CharSequence getReadName() {
      return Read_Name;
    }
    
    /** Sets the value of the 'Read_Name' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder setReadName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.Read_Name = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'Read_Name' field has been set */
    public boolean hasReadName() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'Read_Name' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder clearReadName() {
      Read_Name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'Flag' field */
    public java.lang.Integer getFlag() {
      return Flag;
    }
    
    /** Sets the value of the 'Flag' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder setFlag(int value) {
      validate(fields()[5], value);
      this.Flag = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'Flag' field has been set */
    public boolean hasFlag() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'Flag' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder clearFlag() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'TLen' field */
    public java.lang.Integer getTLen() {
      return TLen;
    }
    
    /** Sets the value of the 'TLen' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder setTLen(int value) {
      validate(fields()[6], value);
      this.TLen = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'TLen' field has been set */
    public boolean hasTLen() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'TLen' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder clearTLen() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'Tags' field */
    public java.nio.ByteBuffer getTags() {
      return Tags;
    }
    
    /** Sets the value of the 'Tags' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder setTags(java.nio.ByteBuffer value) {
      validate(fields()[7], value);
      this.Tags = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'Tags' field has been set */
    public boolean hasTags() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'Tags' field */
    public com.sg.secram.avro.ReadHeaderAvro.Builder clearTags() {
      Tags = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public ReadHeaderAvro build() {
      try {
        ReadHeaderAvro record = new ReadHeaderAvro();
        record.Order = fieldSetFlags()[0] ? this.Order : (java.lang.Integer) defaultValue(fields()[0]);
        record.Ref_len = fieldSetFlags()[1] ? this.Ref_len : (java.lang.Integer) defaultValue(fields()[1]);
        record.Next_POS = fieldSetFlags()[2] ? this.Next_POS : (java.lang.Long) defaultValue(fields()[2]);
        record.Bin_mq_nl = fieldSetFlags()[3] ? this.Bin_mq_nl : (java.lang.Integer) defaultValue(fields()[3]);
        record.Read_Name = fieldSetFlags()[4] ? this.Read_Name : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.Flag = fieldSetFlags()[5] ? this.Flag : (java.lang.Integer) defaultValue(fields()[5]);
        record.TLen = fieldSetFlags()[6] ? this.TLen : (java.lang.Integer) defaultValue(fields()[6]);
        record.Tags = fieldSetFlags()[7] ? this.Tags : (java.nio.ByteBuffer) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
